### ISSUE TITLE
Error when you open slides

### ISSUE THREAD

**Issue by melom13** [googleworkspace/slides-api#3]
I'm getting an error when I run the project on Step 8:

- Start generating slides. --
loaded secrets...
authorizing...
getting new auth token...

Enter the code from that page here: events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

(I think this has to do with how I created an OAuth2 Client (Step 5). I have a similar issue at that point in my SPL - I was looking at the codelab to see if you guys had the fix.)

**Comment by jpoehnelt** [comment]
Closing this issue as the repository is archived.
